version: '3'
services:
  app1:
    build: .
    ports:
      - "8087:8081"
    volumes:
      - ./hazelcast.yml:/app/hazelcast.yml
  app2:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./hazelcast.yml:/app/hazelcast.yml
networks:
  default:
    driver: bridge