version: '3'
services:
  app1:
    build: .
    ports:
      - "8087:8081"
    volumes:
      - ./hazelcast.yml:/app/hazelcast.yml
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newsdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  app2:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./hazelcast.yml:/app/hazelcast.yml

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=newsdb
    ports:
      - "5432:5432"
  
  lb:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - app1
      - app2
volumes:
  db-data:
networks:
  default:
    driver: bridge