#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/newsdb
#    driverClassName : org.postgresql.Driver
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName : org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: taazakhabar
server:
  port: 8081
taazakhabar:
  client:
    hackernews:
      baseuri: https://hacker-news.firebaseio.com/v0
      endpoints:
        topstory: /topstories.json
        item: /item/{id}.json
      cache:
        ttl: 1
      item:
        limit: 10


