spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    driverClassName : org.postgresql.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: taazakhabar
server:
  port: 8081
taazakhabar:
  client:
    hackernews:
      baseuri: https://hacker-news.firebaseio.com/v0
      endpoints:
        topstory: /topstories.json
        item: /item/{id}.json
      cache:
        ttl: 15
      item:
        limit: 10
#     threads:
#        max-thread: 10 #Configure no. of threads as per the requirement and infra available


